(()=>{
  'use strict';
  const $=(s,r=document)=>r.querySelector(s);
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
  const fallback=window.PAWN_CATALOG||[];
  let catalog=fallback;
  function header(){const el=$('[data-header]');if(!el)return;el.innerHTML=`<header class="site-header"><a class="brand" href="index.html">Northline Pawn</a><nav><a href="index.html">Home</a><a href="shop.html">Inventory</a><a href="firearms.html">Firearms</a><a href="contact.html">Visit</a></nav><a class="staff-link" href="admin-login.html">Staff</a></header>`}
  function footer(){const el=$('[data-footer]');if(!el)return;el.innerHTML=`<footer><strong>Northline Pawn & Exchange</strong><span>Browse online. Purchase and pawn services take place in store.</span></footer>`}
  function card(p){return `<article class="product-card"><img src="${p.image||p.image_url||''}" alt="${p.name}" loading="lazy"><div class="product-copy"><div class="meta"><span>${p.category}</span><span>${statusLabel(p.status)}</span></div><h3>${p.name}</h3><p>${p.condition}</p><div class="price-row"><strong>${money(Number(p.price))}</strong><button data-product="${p.id}">View details</button></div></div></article>`}
  function statusLabel(v){return ({available:'In stock',reserved:'Reserved',sold:'Sold',archived:'Archived'})[v]||v||'In stock'}
  async function loadCatalog(){const C=window.PAWN_CONFIG||{};if(!(window.supabase&&C.supabaseUrl&&C.supabasePublishableKey))return;try{const client=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey);const {data,error}=await client.from('products').select('*').in('status',['available','reserved']).order('created_at',{ascending:false});if(!error&&data?.length)catalog=data}catch(e){console.warn('Using fallback catalog',e)}}
  function renderFeatured(){const el=$('[data-featured]');if(el)el.innerHTML=catalog.slice(0,4).map(card).join('')}
  function renderShop(){const el=$('[data-products]');if(!el)return;const search=$('[data-search]'),filter=$('[data-category]');const draw=()=>{const q=(search?.value||'').toLowerCase();const c=filter?.value||'';const items=catalog.filter(p=>(!q||`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q))&&(!c||p.category===c));el.innerHTML=items.map(card).join('')||'<p>No matching inventory.</p>'};search?.addEventListener('input',draw);filter?.addEventListener('change',draw);draw()}
  function modal(id){const p=catalog.find(x=>String(x.id)===String(id));if(!p)return;const el=$('[data-modal]');el.innerHTML=`<div class="modal-card"><button class="close" data-close>×</button><img src="${p.image||p.image_url||''}" alt="${p.name}"><div><span class="pill">${statusLabel(p.status)}</span><h2>${p.name}</h2><h3>${money(Number(p.price))}</h3><p>${p.description}</p><dl><div><dt>Category</dt><dd>${p.category}</dd></div><div><dt>Condition</dt><dd>${p.condition}</dd></div></dl><p class="notice">Available for purchase in store. Call before visiting to confirm availability.</p></div></div>`;el.classList.add('open')}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(b)modal(b.dataset.product);if(e.target.matches('[data-close]')||e.target.matches('[data-modal]'))$('[data-modal]')?.classList.remove('open')});
  document.addEventListener('DOMContentLoaded',async()=>{header();footer();await loadCatalog();renderFeatured();renderShop()});
})();
